Repository testit-tms/adapters-dotnet, pull requests merged in 2023-11, with the labels that each got.

#23 Add real-time test results upload
  Tms.Adapter/README.md
  TmsRunner/Configuration/ClassConfigurationProvider.cs
  TmsRunner/Configuration/EnvConfigurationProvider.cs
  TmsRunner/Handlers/RunEventHandler.cs
  TmsRunner/Models/Config.cs
  TmsRunner/Models/TmsSettings.cs
  TmsRunner/Options/AdapterConfig.cs
  TmsRunner/Program.cs
  TmsRunner/Runner.cs
  TmsRunner/Services/ProcessorService.cs
Labels: enhancement

#24 Disable parallel upload cause of the flakyness
  TmsRunner/Handlers/RunEventHandler.cs
  TmsRunner/Services/ProcessorService.cs
Labels: bug

#26 Supported API-client 2.5.
  Tms.Adapter.Core/Client/Converter.cs
  Tms.Adapter.Core/Client/TmsClient.cs
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/Client/Converter.cs
  TmsRunner/Client/ITmsClient.cs
  TmsRunner/Client/TmsClient.cs
  TmsRunner/Models/Step.cs
  TmsRunner/TmsRunner.csproj
Labels: documentation, enhancement
