Repository testit-tms/adapters-dotnet, pull requests merged in 2025-07, with the labels that each got.

#95 fix: TMS-33524 fix html tags escaping
  Tms.Adapter.Core/Client/TmsClient.cs
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.Core/Utils/HtmlEscapeUtils.cs
  Tms.Adapter.CoreTests/Utils/HtmlEscapeUtilsTests.cs
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/Services/ProcessorService.cs
  TmsRunner/TmsRunner.csproj
  TmsRunner/Utils/HtmlEscapeUtils.cs
Labels: bug

#96 feat: update the package versions.
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: documentation

#97 feat: update the package versions.
  README.md
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: documentation

#98 feat: tms 5.4 support
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.CoreTests/Tms.Adapter.CoreTests.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: documentation, enhancement, tests

#99 feat: last cloud support
  README.md
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.CoreTests/Tms.Adapter.CoreTests.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: documentation, enhancement
