Repository testit-tms/adapters-dotnet, pull requests merged in 2025-04, with the labels that each got.

#86 feat: TMS-32043: add the XmlException output.
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/Managers/ConfigurationManager.cs
  TmsRunner/TmsRunner.csproj
Labels: enhancement

#87 feat: Enhanced Parameter Handling in Test Results
  TmsRunner/Entities/MethodMetadata.cs
  TmsRunner/Utils/LogParser.cs
  TmsRunner/Utils/Reflector.cs
Labels: enhancement

#88 fix: TMS-32229: fix coverage
  .github/workflows/validate.yaml
Labels: bug

#89 feat: TMS-5.3 release support
  README.md
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.CoreTests/Tms.Adapter.CoreTests.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: documentation, enhancement
