Repository testit-tms/adapters-dotnet, pull requests merged in 2025-03, with the labels that each got.

#78 tests: added unit tests for SpecFlowPlugin
  .github/workflows/validate.yaml
  DotnetAdapters.sln
  Tms.Adapter.Core/Configurator/Configurator.cs
  Tms.Adapter.Core/Storage/ResultStorage.cs
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.SpecFlowPlugin/TmsBindingInvoker.cs
  Tms.Adapter.SpecFlowPlugin/TmsHelper.cs
  Tms.Adapter.SpecFlowPlugin/TmsTestTracer.cs
  Tms.Adapter.SpecFlowPluginTests/Helper/CollectionHelper.cs
  Tms.Adapter.SpecFlowPluginTests/Helper/StatusBinding.cs
  Tms.Adapter.SpecFlowPluginTests/Helper/TestsBase.cs
  Tms.Adapter.SpecFlowPluginTests/Tms.Adapter.SpecFlowPluginTests.csproj
  Tms.Adapter.SpecFlowPluginTests/TmsBindingInvokerTests.cs
  Tms.Adapter.SpecFlowPluginTests/TmsHelperTests.cs
  Tms.Adapter.Tests/Tms.Adapter.Tests.csproj
Labels: tests

#80 feature: 1.8.0-TMS-Cloud
  README.md
  Tms.Adapter.Core/Client/ITmsClient.cs
  Tms.Adapter.Core/Client/TmsClient.cs
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.CoreTests/Tms.Adapter.CoreTests.csproj
Labels: enhancement

#81 fix: update package versions.
  Tms.Adapter.Core/Tms.Adapter.Core.csproj
  Tms.Adapter.SpecFlowPlugin/Tms.Adapter.SpecFlowPlugin.csproj
  Tms.Adapter.XUnit/Tms.Adapter.XUnit.csproj
  Tms.Adapter/Tms.Adapter.csproj
  TmsRunner/TmsRunner.csproj
Labels: enhancement

#84 fix: fix logic for no parameters + singleton testrun service for entire app
  TmsRunner/Program.cs
Labels: bug
